# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3036291ff275c849f71079426aa976b1a216ece457bea6095703fe9b372570bb9a7ae5ed3cb136d293e68daf6446a0b59b303337cad3b425014653c76361012c

test:
  secret_key_base: 740b64a5407fad1fd05c9a07ab37c1d2ac6605c7e8bda9e7c1f83384883db82d55ead4279a32469c18ca087f08754fcbcdc22bc85f262afa2495cdb23feb9944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
